"""creare cascade

Revision ID: 7d42da68b5d4
Revises: ded1b5a1ebe0
Create Date: 2022-07-21 18:02:19.546532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d42da68b5d4'
down_revision = 'ded1b5a1ebe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.create_foreign_key(None, 'email', 'user_contact', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.create_foreign_key(None, 'phone', 'user_contact', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.create_foreign_key(None, 'phone', 'user_contact', ['user_id'], ['id'])
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.create_foreign_key(None, 'email', 'user_contact', ['user_id'], ['id'])
    # ### end Alembic commands ###
